#!/usr/bin/env bash
# Regenerate docs/stubs.d.ts — code outline stubs for all packages.
# Usage: bash docs/generate-stubs.sh (run from repo root)
set -euo pipefail

TMPDIR=/tmp/glaude-stubs
rm -rf "$TMPDIR"

packages=(
  "packages/shared:packages_shared"
  "packages/engine:packages_engine"
  "packages/games/abalone:packages_games_abalone"
  "packages/discord-ui:packages_discord-ui"
  "apps/bot:apps_bot"
  "apps/activity:apps_activity"
)

for entry in "${packages[@]}"; do
  pkg="${entry%%:*}"
  dir="${entry##*:}"
  echo "→ $pkg"
  npx tsc -p "$pkg/tsconfig.json" \
    --emitDeclarationOnly \
    --outDir "$TMPDIR/$dir" \
    --noEmit false 2>&1 | grep -v "^$" || true
done

python3 - <<'EOF'
import os, sys

groups = [
    ("packages/shared", "packages_shared", [
        "branded.d.ts", "result.d.ts", "errors.d.ts", "game-types.d.ts", "index.d.ts"
    ]),
    ("packages/engine", "packages_engine", [
        "game-definition.d.ts", "index.d.ts"
    ]),
    ("packages/games/abalone", "packages_games_abalone", [
        "types.d.ts", "board.d.ts", "moves.d.ts", "render.d.ts", "definition.d.ts", "index.d.ts"
    ]),
    ("packages/discord-ui", "packages_discord-ui", [
        "index.d.ts"
    ]),
    ("apps/bot", "apps_bot", [
        "db/schema.d.ts", "db/client.d.ts", "db/repository.d.ts",
        "games/registry.d.ts", "commands/game-start.d.ts", "commands/game-join.d.ts",
        "commands/game-forfeit.d.ts", "commands/game-status.d.ts", "commands/game-move.d.ts",
        "interaction-handler.d.ts", "session-manager.d.ts", "ws-server.d.ts",
        "api-server.d.ts", "client.d.ts", "index.d.ts", "deploy-commands.d.ts"
    ]),
    ("apps/activity", "apps_activity", [
        "src/discord-sdk.d.ts", "src/hex-geometry.d.ts", "src/game-context.d.ts",
        "src/components/BoardSVG.d.ts", "src/components/HUD.d.ts",
        "src/components/WinScreen.d.ts", "src/components/InfoModal.d.ts",
        "src/App.d.ts", "src/main.d.ts"
    ]),
]

base = "/tmp/glaude-stubs"
lines = [
    "// Glaude — Code Outline Stubs",
    "// Auto-generated by: npx tsc -p <pkg>/tsconfig.json --emitDeclarationOnly",
    "// To regenerate: bash docs/generate-stubs.sh",
    "//",
    "// Contains: function signatures, class/enum/type definitions — no implementations.",
    "",
]

for pkg_path, pkg_dir, files in groups:
    lines.append(f"// ═══════════════════════════════════════════════════════")
    lines.append(f"// PACKAGE: {pkg_path}")
    lines.append(f"// ═══════════════════════════════════════════════════════")
    lines.append("")
    for f in files:
        full = os.path.join(base, pkg_dir, f)
        if not os.path.exists(full):
            full_alt = os.path.join(base, pkg_dir, os.path.basename(f))
            if os.path.exists(full_alt):
                full = full_alt
            else:
                continue
        with open(full) as fh:
            content = "\n".join(
                ln for ln in fh.read().splitlines()
                if not ln.startswith("//# sourceMappingURL=")
            ).strip()
        if not content:
            continue
        src_path = f"{pkg_path}/{f.replace('.d.ts', '.ts')}"
        lines.append(f"// ─── {src_path} ───")
        lines.append(content)
        lines.append("")

with open("docs/stubs.d.ts", "w") as out:
    out.write("\n".join(lines) + "\n")

print(f"✓ docs/stubs.d.ts written ({sum(1 for l in lines)} lines)")
EOF
