// Glaude — Code Outline Stubs
// Auto-generated by: npx tsc -p <pkg>/tsconfig.json --emitDeclarationOnly
// To regenerate: bash docs/generate-stubs.sh
//
// Contains: function signatures, class/enum/type definitions — no implementations.

// ═══════════════════════════════════════════════════════
// PACKAGE: packages/shared
// ═══════════════════════════════════════════════════════

// ─── packages/shared/branded.ts ───
declare const brand: unique symbol;
type Brand<T, B> = T & {
    readonly [brand]: B;
};
export type PlayerId = Brand<string, "PlayerId">;
export type SessionId = Brand<string, "SessionId">;
export type GameId = Brand<string, "GameId">;
export declare const PlayerId: (s: string) => PlayerId;
export declare const SessionId: (s: string) => SessionId;
export declare const GameId: (s: string) => GameId;
export {};

// ─── packages/shared/result.ts ───
export type Ok<T> = {
    readonly ok: true;
    readonly value: T;
};
export type Err<E> = {
    readonly ok: false;
    readonly error: E;
};
export type Result<T, E> = Ok<T> | Err<E>;
export declare const ok: <T>(value: T) => Ok<T>;
export declare const err: <E>(error: E) => Err<E>;
export declare const isOk: <T, E>(r: Result<T, E>) => r is Ok<T>;
export declare const isErr: <T, E>(r: Result<T, E>) => r is Err<E>;

// ─── packages/shared/errors.ts ───
export declare class GlaudeError extends Error {
    readonly code: string;
    constructor(message: string, code: string, options?: ErrorOptions);
}

// ─── packages/shared/game-types.ts ───
import type { PlayerId } from "./branded";
export type GamePhase = "CREATED" | "LOBBY" | "PLAYING" | "FINISHED" | "CANCELLED" | "FORFEITED";
export type GameOutcome = {
    readonly kind: "WIN";
    readonly winner: PlayerId;
} | {
    readonly kind: "DRAW";
} | {
    readonly kind: "FORFEIT";
    readonly winner: PlayerId;
    readonly forfeiter: PlayerId;
};
export type PlayerSeat = {
    readonly playerId: PlayerId;
    readonly seatIndex: number;
};

// ─── packages/shared/index.ts ───
export type { Ok, Err, Result } from "./result";
export { ok, err, isOk, isErr } from "./result";
export { GlaudeError } from "./errors";
export { PlayerId, SessionId, GameId } from "./branded";
export type { GamePhase, GameOutcome, PlayerSeat } from "./game-types";

// ═══════════════════════════════════════════════════════
// PACKAGE: packages/engine
// ═══════════════════════════════════════════════════════

// ─── packages/engine/game-definition.ts ───
import type { GameId, GameOutcome, PlayerId, PlayerSeat, Result } from "@glaude/shared";
export interface GameDefinition<TState, TMove, TRenderContext> {
    readonly id: GameId;
    readonly displayName: string;
    readonly players: {
        readonly min: 2;
        readonly max: number;
    };
    initialState(seats: readonly PlayerSeat[]): TState;
    validateMove(state: TState, move: TMove, playerId: PlayerId): Result<void, string>;
    applyMove(state: TState, move: TMove, playerId: PlayerId): TState;
    legalMoves(state: TState, playerId: PlayerId): readonly TMove[];
    currentTurn(state: TState): PlayerId;
    outcome(state: TState): GameOutcome | null;
    /**
     * Returns a player-specific masked view of the state.
     * When defined, the WS server sends each player their own view instead of
     * a shared broadcast. Optional — falls back to serializeState if absent.
     */
    buildPlayerView?(state: TState, playerId: PlayerId, seats: readonly PlayerSeat[]): unknown;
    /**
     * Returns the set of players who must respond in the current phase.
     * When defined, the WS server uses this for move authorization instead of
     * falling back to [currentTurn]. Optional.
     */
    activeRespondents?(state: TState): readonly PlayerId[];
    buildRenderContext(state: TState, seats: readonly PlayerSeat[]): TRenderContext;
    render(ctx: TRenderContext): Promise<Uint8Array>;
    serializeState(state: TState): string;
    deserializeState(raw: string): TState;
    serializeMove(move: TMove): string;
    deserializeMove(raw: string): TMove;
}

// ─── packages/engine/index.ts ───
export type { GameDefinition } from "./game-definition";

// ═══════════════════════════════════════════════════════
// PACKAGE: packages/games/abalone
// ═══════════════════════════════════════════════════════

// ─── packages/games/abalone/types.ts ───
import type { PlayerId } from "@glaude/shared";
export type AxialCoord = {
    readonly q: number;
    readonly r: number;
};
/** Index into HEX_DIRECTIONS (0-5) */
export type HexDir = 0 | 1 | 2 | 3 | 4 | 5;
export type Cell = {
    readonly kind: "empty";
} | {
    readonly kind: "marble";
    readonly owner: PlayerId;
};
export type AbaloneState = {
    readonly board: Map<string, Cell>;
    readonly turn: PlayerId;
    readonly capturedBy: Readonly<Record<string, number>>;
    readonly moveNumber: number;
};
export type AbaloneMove = {
    readonly type: "inline";
    readonly marbles: readonly AxialCoord[];
    readonly direction: HexDir;
} | {
    readonly type: "broadside";
    readonly marbles: readonly AxialCoord[];
    readonly direction: HexDir;
};
export type AbaloneRenderContext = {
    readonly state: AbaloneState;
    readonly players: ReadonlyArray<{
        readonly playerId: PlayerId;
        readonly seatIndex: number;
    }>;
};

// ─── packages/games/abalone/board.ts ───
import type { PlayerId } from "@glaude/shared";
import type { AxialCoord, AbaloneState, Cell, HexDir } from "./types.js";
export declare const HEX_DIRECTIONS: readonly AxialCoord[];
/** Opposite direction index (dir + 3) % 6 */
export declare const opposite: (dir: HexDir) => HexDir;
export declare const coordKey: (c: AxialCoord) => string;
export declare const parseKey: (key: string) => AxialCoord;
export declare const addCoord: (a: AxialCoord, b: AxialCoord) => AxialCoord;
export declare const step: (c: AxialCoord, dir: HexDir) => AxialCoord;
/** The 61 valid axial coords: max(|q|,|r|,|q+r|) <= 4 */
export declare const VALID_CELLS: ReadonlySet<string>;
export declare const isOnBoard: (c: AxialCoord) => boolean;
/**
 * Standard starting layout.
 * Player at seat 0 = "black" (top, r <= -3 / partial r=-2)
 * Player at seat 1 = "white" (bottom, r >= 3 / partial r=2)
 */
export declare const initialBoard: (blackPlayer: PlayerId, whitePlayer: PlayerId) => Map<string, Cell>;
/** Count marbles on board for a given player */
export declare const countMarbles: (board: Map<string, Cell>, owner: PlayerId) => number;
/** Build an AbaloneState with a fresh initial board */
export declare const initialState: (blackPlayer: PlayerId, whitePlayer: PlayerId) => AbaloneState;

// ─── packages/games/abalone/moves.ts ───
import type { PlayerId } from "@glaude/shared";
import type { Result } from "@glaude/shared";
import type { AbaloneMove, AbaloneState } from "./types.js";
export declare const validateMove: (state: AbaloneState, move: AbaloneMove) => Result<void, string>;
export declare const applyMove: (state: AbaloneState, move: AbaloneMove) => AbaloneState;
/**
 * Returns the PlayerId of the winner (the player who has pushed off 6 opponent marbles),
 * or null if the game is still in progress.
 */
export declare const isWon: (state: AbaloneState) => PlayerId | null;
/**
 * Generate all legal moves for the current player.
 */
export declare const legalMoves: (state: AbaloneState) => AbaloneMove[];

// ─── packages/games/abalone/render.ts ───
import type { AbaloneRenderContext } from "./types.js";
export declare const renderAbalone: (ctx: AbaloneRenderContext) => Promise<Uint8Array>;

// ─── packages/games/abalone/definition.ts ───
import type { GameDefinition } from "@glaude/engine";
import type { AbaloneMove, AbaloneRenderContext, AbaloneState } from "./types.js";
export declare const abaloneDefinition: GameDefinition<AbaloneState, AbaloneMove, AbaloneRenderContext>;

// ─── packages/games/abalone/index.ts ───
export type { AxialCoord, HexDir, Cell, AbaloneState, AbaloneMove, AbaloneRenderContext } from "./types.js";
export { HEX_DIRECTIONS, opposite, coordKey, parseKey, addCoord, step, VALID_CELLS, isOnBoard, initialBoard, initialState, countMarbles, } from "./board.js";
export { validateMove, applyMove, legalMoves, isWon } from "./moves.js";
export { abaloneDefinition } from "./definition.js";
export { renderAbalone } from "./render.js";

// ═══════════════════════════════════════════════════════
// PACKAGE: packages/discord-ui
// ═══════════════════════════════════════════════════════

// ═══════════════════════════════════════════════════════
// PACKAGE: apps/bot
// ═══════════════════════════════════════════════════════

// ─── apps/bot/db/client.ts ───
import { drizzle } from "drizzle-orm/better-sqlite3";
import * as schema from "./schema.js";
export type Db = ReturnType<typeof createDb>;
export declare const createDb: (dbPath: string) => ReturnType<typeof drizzle<typeof schema>>;

// ─── apps/bot/db/repository.ts ───
import type { Db } from "./client.js";
import { gameSessions, sessionPlayers } from "./schema.js";
import type { PlayerId, PlayerSeat } from "@glaude/shared";
import type { LobbySession, PlayingSession, EndedSession } from "../session-manager.js";
export declare const ensurePlayer: (db: Db, discordId: PlayerId, username: string) => void;
export declare const persistLobby: (db: Db, session: LobbySession) => void;
export declare const addSessionPlayer: (db: Db, sessionId: string, seat: PlayerSeat) => void;
export declare const persistPlaying: (db: Db, session: PlayingSession) => void;
export declare const persistMoveAndState: (db: Db, session: PlayingSession, playerId: PlayerId, serializedMove: string, moveNumber: number) => void;
export declare const persistEnded: (db: Db, session: EndedSession) => void;
export declare const updateMessageId: (db: Db, sessionId: string, messageId: string) => void;
export type RecoveredLobby = {
    phase: "LOBBY";
    row: typeof gameSessions.$inferSelect;
    seats: (typeof sessionPlayers.$inferSelect)[];
};
export type RecoveredPlaying = {
    phase: "PLAYING";
    row: typeof gameSessions.$inferSelect;
    seats: (typeof sessionPlayers.$inferSelect)[];
};
export type RecoveredSession = RecoveredLobby | RecoveredPlaying;
export declare const loadActiveSessions: (db: Db) => RecoveredSession[];

// ─── apps/bot/games/registry.ts ───
import type { GameDefinition } from "@glaude/engine";
export declare const findGame: (id: string) => GameDefinition<any, any, any> | undefined;
export declare const listGames: () => readonly string[];

// ─── apps/bot/commands/game-start.ts ───
import type { ChatInputCommandInteraction } from "discord.js";
import type { SessionManager } from "../session-manager.js";
import type { Db } from "../db/client.js";
export declare const execute: (interaction: ChatInputCommandInteraction, sessionManager: SessionManager, db: Db) => Promise<void>;

// ─── apps/bot/commands/game-join.ts ───
import { type ChatInputCommandInteraction } from "discord.js";
import type { SessionManager } from "../session-manager.js";
import type { Db } from "../db/client.js";
export declare const execute: (interaction: ChatInputCommandInteraction, sessionManager: SessionManager, db: Db) => Promise<void>;

// ─── apps/bot/commands/game-forfeit.ts ───
import type { ChatInputCommandInteraction } from "discord.js";
import type { SessionManager } from "../session-manager.js";
export declare const execute: (interaction: ChatInputCommandInteraction, sessionManager: SessionManager) => Promise<void>;

// ─── apps/bot/commands/game-status.ts ───
import { type ChatInputCommandInteraction } from "discord.js";
import type { SessionManager } from "../session-manager.js";
export declare const execute: (interaction: ChatInputCommandInteraction, sessionManager: SessionManager) => Promise<void>;

// ─── apps/bot/commands/game-move.ts ───
import { type ChatInputCommandInteraction } from "discord.js";
import type { SessionManager } from "../session-manager.js";
export declare const execute: (interaction: ChatInputCommandInteraction, sessionManager: SessionManager) => Promise<void>;

// ─── apps/bot/interaction-handler.ts ───
import type { Client } from "discord.js";
import type { SessionManager } from "./session-manager.js";
import type { Db } from "./db/client.js";
export declare const registerInteractionHandler: (client: Client, sessionManager: SessionManager, db: Db) => void;

// ─── apps/bot/session-manager.ts ───
import type { GameDefinition } from "@glaude/engine";
import { PlayerId } from "@glaude/shared";
import type { GameId, GameOutcome, PlayerSeat, Result } from "@glaude/shared";
import type { Db } from "./db/client.js";
export type LobbySession = {
    readonly phase: "LOBBY";
    readonly channelId: string;
    readonly sessionId: string;
    readonly gameId: GameId;
    readonly hostId: PlayerId;
    readonly seats: readonly PlayerId[];
    readonly messageId?: string;
};
export type PlayingSession = {
    readonly phase: "PLAYING";
    readonly channelId: string;
    readonly sessionId: string;
    readonly gameId: GameId;
    readonly seats: readonly PlayerSeat[];
    readonly definition: GameDefinition<any, any, any>;
    readonly state: unknown;
    readonly messageId?: string;
};
export type EndedSession = {
    readonly phase: "FINISHED" | "FORFEITED";
    readonly channelId: string;
    readonly sessionId: string;
    readonly gameId: GameId;
    readonly seats: readonly PlayerSeat[];
    readonly outcome: GameOutcome;
    readonly messageId?: string;
};
export type Session = LobbySession | PlayingSession | EndedSession;
export declare class SessionManager {
    #private;
    constructor(db: Db);
    recover(): void;
    createLobby(channelId: string, gameId: string, hostId: PlayerId): Result<LobbySession, string>;
    joinLobby(channelId: string, playerId: PlayerId): Result<LobbySession | PlayingSession, string>;
    forfeit(channelId: string, playerId: PlayerId): Result<EndedSession, string>;
    makeMove(channelId: string, playerId: PlayerId, move: unknown): Result<{
        session: PlayingSession | EndedSession;
        renderCtx: unknown;
    }, string>;
    /**
     * Upserts the player record then creates or joins a lobby for `channelId`.
     * First caller becomes the host (LOBBY); second caller starts the game (PLAYING).
     * Returns the resulting session, or an error string if the channel already has
     * an active session the player can't join (e.g. game in progress with other players).
     */
    autoJoin(channelId: string, gameId: string, playerId: PlayerId, username: string): Result<LobbySession | PlayingSession, string>;
    setMessageId(channelId: string, messageId: string): void;
    getSession(channelId: string): Session | undefined;
    getSessionBySessionId(sessionId: string): Session | undefined;
    /** Channel ID for a given session ID (O(n) — sessions are small) */
    getChannelId(sessionId: string): string | undefined;
}

// ─── apps/bot/ws-server.ts ───
import { WebSocketServer } from "ws";
import type { SessionManager } from "./session-manager.js";
export declare function startWsServer(sessions: SessionManager): WebSocketServer;

// ─── apps/bot/api-server.ts ───
export declare function startApiServer(): void;

// ─── apps/bot/client.ts ───
import { Client } from "discord.js";
export declare const createClient: () => Client;

// ─── apps/bot/index.ts ───
export {};

// ═══════════════════════════════════════════════════════
// PACKAGE: apps/activity
// ═══════════════════════════════════════════════════════

// ─── apps/activity/src/discord-sdk.ts ───
import { DiscordSDK, type DiscordSDKMock } from "@discord/embedded-app-sdk";
export type SdkAuth = {
    userId: string;
    username: string;
    avatarUrl: string | null;
    sessionId: string | null;
    wsUrl?: string;
};
export declare function initDiscordSdk(): Promise<SdkAuth>;
export declare function getDiscordSdk(): DiscordSDK | DiscordSDKMock | null;

// ─── apps/activity/src/hex-geometry.ts ───
import type { AxialCoord, HexDir } from "@glaude/game-abalone/types";
export declare const HEX_RADIUS = 32;
/** SVG canvas dimensions and center */
export declare const SVG_WIDTH = 560;
export declare const SVG_HEIGHT = 600;
export declare const CX: number;
export declare const CY: number;
/** Axial → pixel (flat-top layout) */
export declare function axialToPixel(coord: AxialCoord): {
    x: number;
    y: number;
};
/** Six vertices of a flat-top hexagon centered at (cx, cy) */
export declare function hexVertices(cx: number, cy: number, radius?: number): string;
/** Pixel direction unit vector for a given HexDir */
export declare function directionVector(dir: HexDir): {
    dx: number;
    dy: number;
};

// ─── apps/activity/src/game-context.ts ───
import { type ReactNode } from "react";
import { PlayerId } from "@glaude/shared";
import type { AbaloneState, AbaloneMove } from "@glaude/game-abalone/types";
import type { SdkAuth } from "./discord-sdk.js";
export declare const BLACK_ID: PlayerId;
export declare const WHITE_ID: PlayerId;
export type GameOver = {
    kind: "WIN" | "FORFEIT" | "DRAW";
    winner?: string;
    forfeiter?: string;
};
type GameContextValue = {
    state: AbaloneState;
    myPlayerId: PlayerId;
    opponentId: PlayerId;
    blackPlayerId: PlayerId;
    myUsername: string;
    myAvatarUrl: string | null;
    sendMove: (move: AbaloneMove) => void;
    forfeit: () => void;
    startNewGame: () => void;
    connected: boolean;
    gameOver: GameOver | null;
};
export declare function GameProvider({ auth, children }: {
    auth: SdkAuth;
    children: ReactNode;
}): import("react/jsx-runtime").JSX.Element;
export declare function useGame(): GameContextValue;
export {};

// ─── apps/activity/src/components/BoardSVG.ts ───
export declare function BoardSVG(): import("react/jsx-runtime").JSX.Element;

// ─── apps/activity/src/components/HUD.ts ───
export declare function HUD(): import("react/jsx-runtime").JSX.Element;

// ─── apps/activity/src/components/WinScreen.ts ───
export declare function WinScreen(): import("react/jsx-runtime").JSX.Element | null;

// ─── apps/activity/src/components/InfoModal.ts ───
export declare function InfoModal({ onClose }: {
    onClose: () => void;
}): import("react/jsx-runtime").JSX.Element;

// ─── apps/activity/src/App.ts ───
import type { SdkAuth } from "./discord-sdk.js";
export declare function App({ auth }: {
    auth: SdkAuth;
}): import("react/jsx-runtime").JSX.Element;

// ─── apps/activity/src/main.ts ───
export {};

